#!/bin/zsh

# the kernel takes care of that
#if [[ "$-" =~ "i" ]] && [ -d /dev/cgroup/cpu/user ] && [ -w /dev/cgroup/cpu/user ]; then
#   mkdir -m 0700 /dev/cgroup/cpu/user/$$
#   echo $$ > /dev/cgroup/cpu/user/$$/tasks
#   echo "1" > /dev/cgroup/cpu/user/$$/notify_on_release
#fi
