#!/bin/zsh

export KEYTIMEOUT=1
export HISTSIZE=1000
export SAVEHIST=1000
export HISTFILE=~/.history
export EDITOR=nvim
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export PAGER='less -X -M'
#export MANPAGER="nvim -c 'set ft=man' -"
export LS_OPT2='--color=auto'

typeset -ga preexec_functions
typeset -ga precmd_functions
typeset -ga chpwd_functions
setopt prompt_subst

PATH="/usr/lib/ccache/bin:${PATH}"
CCACHE_DIR="/var/cache/ccache"
DISTCC_DIR="/var/tmp/portage/.distcc"

ulimit -s unlimited
