#!/bin/zsh

setopt HIST_IGNORE_DUPS
setopt HIST_EXPIRE_DUPS_FIRST
setopt histignorespace
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY
setopt no_beep
setopt autocd
setopt auto_pushd
setopt pushdignoredups
setopt extended_glob
setopt vi
setopt zle

autoload -U zmv
