#!/bin/zsh

rationalise-dot() {
    if [[ $KEYS = "." && $LBUFFER = *.. ]]; then
        LBUFFER+=/..
    else
        zle .self-insert "$@"
    fi
}
zle -N self-insert rationalise-dot

resolve-alias() {
    # Recursively resolve aliases and echo the command.
    typeset -a cmd
    cmd=(${(z)1})
    while (( ${+aliases[$cmd[1]]} )) \
        && [[ ${aliases[$cmd[1]]} != $cmd ]]; do
      cmd=(${(z)aliases[${cmd[1]}]})
    done
    echo $cmd
}

alias mv='mv -v'
alias cp='cp -v'
alias rm='rm -v'
alias lsd='ls -d *(/)'
alias lld='ls -l -d *(/)'
alias chown='chown -v'
alias chgrp='chgrp -v'
alias less='less -i'
alias scpresume='rsync --partial --progress --rsh=ssh --inplace --timeout=10'
alias cal='cal -m'
alias bc='bc -l -q'
alias e='smartextract'

alias icat='kitty +kitten icat'

if [ -e /usr/bin/startx ] ; then
    alias sx='tmux new-session -d -s x11 "startx" && exit'
    alias xstart='startx "/usr/local/bin/xstarter xterm" -- :1'
fi

# suffix aliases
alias -s c=vim
alias -s java=vim
alias -s pl=vim
alias -s tex=vim

if [ "$TERM" = dumb ] || [ ! -x /usr/bin/grc ] ; then
    alias ll='ls -l'
    alias llh='ls -l -h'
fi
