#!/bin/zsh

alias mv='mv -v'
alias cp='cp -v'
alias rm='rm -v'
alias lsd='ls -d *(/)'
alias lld='ls -l -d *(/)'
alias chown='chown -v'
alias chgrp='chgrp -v'
alias less='less -r -i'
alias scpresume="rsync --partial --progress --rsh=ssh --inplace --timeout=10"
alias cal="cal -m"
alias e='smartextract'
alias -g ...='../..'
alias -g ....='../../..'
alias -g .....='../../../..'

if [ -e /usr/bin/startx ] ; then
	alias sx='tmux new-session -d -s x11 "startx" && exit'
	alias xstart='startx "/usr/local/bin/xstarter xterm" -- :1'
fi

# suffix aliases
alias -s c=vim
alias -s java=vim
alias -s pl=vim
alias -s tex=vim

if [ "$TERM" = dumb ] || [ ! -x /usr/bin/grc ] ; then
	alias ll='ls -l'
fi
