#!/bin/zsh

export GIT_AUTHOR_NAME='shdb'
export GIT_AUTHOR_EMAIL='shadowblade@gmx.ch'
export GIT_COMMITTER_NAME=$GIT_AUTHOR_NAME
export GIT_COMMITTER_EMAIL=$GIT_AUTHOR_EMAIL
# gitpatch() {
#     git co master; git svn rebase; git co 
# }
