#!/bin/zsh

if [[ -f /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]]; then
    source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
elif [[ -f /usr/share/zsh/site-functions/zsh-syntax-highlighting.zsh ]]; then
    source /usr/share/zsh/site-functions/zsh-syntax-highlighting.zsh
fi
