#!/bin/zsh

smartextract () {
    if [ -f $1 ]; then
        case $1 in
            *.tar.bz2)   tar -jxvf $1        ;;
            *.tbz2)      tar -jxvf $1        ;;
            *.tar.xz)    tar -Jxvf $1        ;;
            *.tar.gz)    tar -zxvf $1        ;;
            *.tgz)       tar -zxvf $1        ;;
            *.tar)       tar -xvf $1         ;;
            *.bz2)       bunzip2 $1          ;;
            *.gz)        gunzip $1           ;;
            *.zip)       unzip $1            ;;
            *.Z)         uncompress $1       ;;
            *.7z)        7z x $1             ;;
            *.rar|*.001) unrar x $1          ;;
            *.ace)       unace x $1          ;;
            *)           echo "'$1' cannot be extracted via smartextract()" ;;
        esac
    else
        echo "'$1' is not a valid file"
    fi
}
